### ISSUE TITLE
Use item index in map() callback 

### ISSUE THREAD

**Issue by jroenf** [jkoudys/immutable.php#9]
I'd like to have the item index available during mapping. If you want, I can create a pull request. For backwards compatibility, index can be used as a second argument of the callback.

**Comment by jkoudys** [comment]
@jroenf sorry for not updating the issue. I think I'd originally left the index out so the callbacks would be compatible with `array_map`, but ultimately decided that `array_map`'s quasi-merge approach with multiple arrays is a bit silly and not very popular anyways, and you can easily replicate its behaviour if you have the index.

e.g. instead of `array_map(function ($a, $b) { return "$a :: $b"; }, $arrOne, $arrTwo)`, you could simply say: `$immArrOne->map(function ($a, $i) { return $a . ' :: ' . $immArrTwo[$i]; });`. This change will break anyone who wants to use an old multi-argument function they had written for `array_map`, but I have pored over many repos and found nobody doing that, so I doubt it's a behaviour anyone is even aware of.
